### ISSUE TITLE
mandel_vectorize.py - TypeError: argument #6 has invalid type

### ISSUE THREAD

**Issue by bgreen-litl** [ContinuumIO/numbapro-examples#6] opened 2015-04-29 20:44 UTC
I'm running the vectorized mandelbrot set example in an ipython notebook.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-2fd5fc9b9b75> in <module>()
      2 height = 750 * 10
      3 ts = timer()
----> 4 pixels = create_fractal(-2.0, 1.0, -1.0, 1.0, width, height, 20)
      5 te = timer()
      6 print('time: %f' % (te - ts))

<ipython-input-1-e542c31729c4> in create_fractal(min_x, max_x, min_y, max_y, width, height, iters)
     31     return mandel(tids, np.float64(min_x), np.float64(max_x), np.float64(min_y),
     32                   np.float64(max_y), np.uint32(height), np.uint32(width),
---> 33                   np.uint32(iters))

/usr/local/anaconda/lib/python2.7/site-packages/numbapro/cudavec/dispatch.pyc in __call__(self, *args, **kws)

/usr/local/anaconda/lib/python2.7/site-packages/numbapro/common/deviceufunc.pyc in call(cls, typemap, args, kws)

/usr/local/anaconda/lib/python2.7/site-packages/numbapro/common/deviceufunc.pyc in get_arguments(self)

/usr/local/anaconda/lib/python2.7/site-packages/numbapro/common/deviceufunc.pyc in _fill_arrays(self)

TypeError: argument #6 has invalid type

**Comment by sklam** [comment] 2015-04-29 20:56
It works with numbapro 0.18.0 and numpy 1.9.2 on OSX python2.7.  If you have an older version, you can update by `conda install numbapro`.

**Comment by bgreen-litl** [comment] 2015-04-30 01:29
I just installed anaconda and numbapro on this particular machine, so everything should be up to date...

    $ conda list | grep numba
    numba                     0.18.2               np19py27_1
    numbapro                  0.18.0              np19py27_p2
    numbapro_cudalib          0.2                           0

    $ conda list | grep numpy
    numpy                     1.9.2                   py27_p0  [mkl]

This is however ubuntu linux-64 not OSX.

    $ uname -a
    Linux ownage 3.16.0-34-generic #47~14.04.1-Ubuntu SMP Fri Apr 10 17:49:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

    $ dpkg --get-selections | grep cuda
    cuda						install
    cuda-7-0					install
    cuda-command-line-tools-7-0			install
    cuda-core-7-0					install
    cuda-cublas-7-0					install
    cuda-cublas-dev-7-0				install
    cuda-cudart-7-0					install
    cuda-cudart-dev-7-0				install
    cuda-cufft-7-0					install
    cuda-cufft-dev-7-0				install
    cuda-curand-7-0					install
    cuda-curand-dev-7-0				install
    cuda-cusolver-7-0				install
    cuda-cusolver-dev-7-0				install
    cuda-cusparse-7-0				install
    cuda-cusparse-dev-7-0				install
    cuda-documentation-7-0				install
    cuda-driver-dev-7-0				install
    cuda-drivers					install
    cuda-license-7-0				install
    cuda-misc-headers-7-0				install
    cuda-npp-7-0					install
    cuda-npp-dev-7-0				install
    cuda-nvrtc-7-0					install
    cuda-nvrtc-dev-7-0				install
    cuda-repo-ubuntu1404-7-0-local			install
    cuda-runtime-7-0				install
    cuda-samples-7-0				install
    cuda-toolkit-7-0				install
    cuda-visual-tools-7-0				install
    libcuda1-346					install

**Comment by bgreen-litl** [comment] 2015-04-30 13:33
Ok. I tried in OSX now and also directly from the command line as well and I get the same results.

    $ conda list | grep numbapro
    numbapro                  0.18.0              np19py27_p2
    numbapro_cudalib          0.2                           0

    $ conda list | grep numpy
    numpy                     1.9.2                   py27_p0  [mkl]

    $ python --version
    Python 2.7.9 :: Anaconda 2.1.0 (x86_64)

$ python mandel_vectorize.py
Vendor:  Continuum Analytics, Inc.
Package: numbapro
Message: trial mode expires in 30 days
Traceback (most recent call last):
  File "mandel_vectorize.py", line 51, in <module>
    main()
  File "mandel_vectorize.py", line 41, in main
    pixels = create_fractal(-2.0, 1.0, -1.0, 1.0, width, height, 20)
  File "mandel_vectorize.py", line 35, in create_fractal
    np.uint32(iters))
  File "/opt/anaconda1anaconda2anaconda3/lib/python2.7/site-packages/numbapro/cudavec/dispatch.py", line 37, in __call__
  File "/opt/anaconda1anaconda2anaconda3/lib/python2.7/site-packages/numbapro/common/deviceufunc.py", line 195, in call
  File "/opt/anaconda1anaconda2anaconda3/lib/python2.7/site-packages/numbapro/common/deviceufunc.py", line 151, in get_arguments
  File "/opt/anaconda1anaconda2anaconda3/lib/python2.7/site-packages/numbapro/common/deviceufunc.py", line 58, in _fill_arrays
TypeError: argument #6 has invalid type

**Comment by gmarkall** [comment] 2015-04-30 13:38
I can replicate this on Linux with Numba 0.18.2/Numbapro 0.18.0 and also with the master branch of both of these.

**Comment by sklam** [comment] 2015-04-30 17:04
Sorry, I can confirm the issue on OSX as well. I did not realize I have an out-of-sync copy of the `mandel_vectorize.py`.  

The issue has been fixed in numbapro (thanks @gmarkall).  We have planned a release by the end of May.  For now, you can workaround the problem by removing the ``np.uint32``.  So like:

```python
return mandel(tids, np.float64(min_x), np.float64(max_x), np.float64(min_y),
                  np.float64(max_y), height, width, iters)
```

The problem was that numbapro did not recognize ``np.uint32``, which was there in the example because old numbapro did not match regular `int` types to ``uint32`` as required by the signature.

**Comment by bgreen-litl** [comment] 2015-05-01 00:20
Thank you. The work around got me going for now.

**Closed** 2016-01-04 18:11 UTC
